scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    # The filter uses the UGV's base link as the reference frame
    box_frame: base_link

    # X-axis filtering (front to back):
    # The UGV's wheels are positioned at ±0.10875m from the base link.
    # These limits ensure the filter covers slightly beyond the wheels.
    min_x: -0.18  # Back of the UGV (slightly beyond back wheels)
    max_x: 0.18   # Front of the UGV (slightly beyond front wheels)

    # Y-axis filtering (side to side):
    # The wheels are positioned at ±0.12569m on the y-axis.
    # These limits ensure the filter covers slightly beyond the sides of the UGV.
    min_y: -0.18  # Left side (slightly beyond the left wheels)
    max_y: 0.18   # Right side (slightly beyond the right wheels)

    # Z-axis filtering (height):
    # The LiDAR is mounted 0.1523m above the base link.
    # These limits ensure the filter captures the area from below the UGV to above the LiDAR.
    min_z: -1.0   # Below the UGV
    max_z: 1.0    # Above the UGV and LiDAR
